services:
  backend:
    build: .
    env_file:
      - .env
    environment:
      - PORT=8000
      - MONGODB_URI=mongodb+srv://maazansari:ScafdfB2AC3R1aFb@cluster0.ajtrgne.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - FIREBASE_APIKEY= "AIzaSyBsTJF134vv8FcktrIA8LnHLoDH9ZCqxFk"
      - FIREBASE_AUTHDOMAIN= "smartreport-8317a.firebaseapp.com"
      - FIREBASE_PROJECTID= "smartreport-8317a"
      - FIREBASE_STORAGEBUCKET= "smartreport-8317a.appspot.com"
      - FIREBASE_MESSEGING_SENDER= "752036967730"
      - FIREBASE_APPID= "1:752036967730:web:5124696afa84c72fc2532b"
      - FIREBASE_MESSUREMENTID= "G-5K32L5865V"
      - CORS_ORIGIN="http://localhost:5173"
    ports:
      - "8000:8000"
